# Generated by Django 3.1.3 on 2021-02-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=70, unique=True, verbose_name='Vin')),
                ('color', models.CharField(max_length=70, verbose_name='Color')),
                ('brand', models.CharField(max_length=70, verbose_name='Brand')),
                ('car_type', models.IntegerField(choices=[(1, 'Cobalt'), (2, 'Matiz'), (3, 'Spark'), (4, 'Jentra')], verbose_name='Car_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
